workflows:
  android-build:
    name: Android Debug Build

    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/**

    triggering:
      events:
        - push
        - pull_request
